name: Deploy on EC2 Production

on:
  push:
    branches: 
      - dev
      - main
  pull_request:
    branches: [dev]

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Testing Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          REMOTE_HOST: ${{ secrets.TEST_HOST_DNS }}
          REMOTE_USER: ${{ secrets.TEST_USERNAME }}
          TARGET: ${{ secrets.TEST_PROD_TARGET_DIR }}
